### ISSUE TITLE
[🐛] Gcloud config dir is not writable

### ISSUE THREAD

**Issue by lancehudson** [snyk/kubernetes-monitor#1099]
- `kubernetes-monitor version 1.92.2` 
- `Cloud runtime GKE`

### Expected behaviour
Gcloud docker auth helper works

### Actual behaviour
gcloud is unable to create temp tokens because `/srv/app/.config/gcloud` is not writable

### Steps to reproduce
Deploy monitor with helm using gcloud cred helpers
```
          {
            "credHelpers": {
              "gcr.io": "gcloud",
              "us.gcr.io": "gcloud",
              "eu.gcr.io": "gcloud",
              "asia.gcr.io": "gcloud",
              "staging-k8s.gcr.io": "gcloud",
              "marketplace.gcr.io": "gcloud"
            }
          }
```

**Comment by kat1906** [comment]
@lancehudson what version of GKE are you using?

**Comment by dkontorovskyy** [comment]
@lancehudson thanks for opening this issue!

Could you provide the K8S version you're running, and any configuration technicalities in your cluster, so it would be easier for us to reproduce, please?
Are your GCR and GKE in the same project or any other setup info that might help us to reproduce the issue?

Best,
Daniel

**Comment by lancehudson** [comment]
GKE v1.20.11-gke.1300
Same Project

It isn't related to the cluster. Your HELM chart marks the root FS as ready only (GOOD), but the gcloud cli defaults to storing its config in `/srv/app/.config/gcloud`. It isn't writeable because it isn't marked as a volume and the root is read only.

This is my helm values file:

```
workloadPoliciesMap: snyk-monitor-workload-policies
nodeSelector:
  iam.gke.io/gke-metadata-server-enabled: "true"
requests:
  ephemeral-storage: 50Gi
limits:
  ephemeral-storage: 50Gi
clusterName: "{{name}}"
psp:
  enabled: true
securityContext:
  fsGroup: 65534
volumes:
  projected:
    serviceAccountToken: true
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
rbac:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: "snyk@{{project}}.iam.gserviceaccount.com"
envs:
  - name: CLOUDSDK_CONFIG
    value: "/var/tmp/gcloud"

```

I have worked around the issue by setting the ENV var `CLOUDSDK_CONFIG` which lets me specify a dir for gcloud to use.
