### ISSUE TITLE
[🙏] Add support for extra volumes and volumemounts in `snyk-monitor` helm chart

### ISSUE THREAD

**Issue by Laffs2k5** [snyk/kubernetes-monitor#1165]
**Describe the user need**

I would love to see the `snyk-monitor` helm chart extended with the possibility to add custom volumes and volume mounts. From other helm charts I'm used to see `extraVolumes: []` and `extraVolumeMounts: []` in the values.yaml.

**Describe expected behaviour**

I would like the possibility to specify something like this in our values.yaml (like in the official filebeat chart):
```yaml
extraVolumes:
  - name: extras
    emptyDir: {}
extraVolumeMounts:
  - name: extras
    mountPath: /usr/share/extras
    readOnly: true
```

Or something more advanced (which would be our use case):
```yaml
  extraVolumes:
    - csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "my-key-vault-from-azure" # created elsewhere
      name: "my-kv-volume"
  extraVolumeMounts:
    - mountPath: "/mnt/my-kv-volume"
      name: "my-kv-volume"
      readOnly: true
```

**Additional context**

Background: We are migrating our Azure Kubernetes clusters to using [Azure Key Vault Provider for Secrets Store CSI Driver](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/). This allows us to have secrets from our Azure key vaults mounted into pods as either Kubernetes `volumeMount` (files) or Kubernetes `secret`. In order to have the Kubernetes secrets automatically created from a Key Vault secret (by the provider) it is a requirement by the provider that the csi volume is mounted in at least one container. I'm not currently able to achieve this with the current  `snyk-monitor` helm chart.

Our deployment and upgrade processes are fully automated through the use of ArgoCD and running manual steps (ex. manual fiddling with kubectl) as part of the process is not an option.

**Implementation**

Implementation should be a breeze and I'll be happy to provide a pull request;

Above [snyk-monitor/templates/deployment.yaml#L100](https://github.com/snyk/kubernetes-monitor/blob/master/snyk-monitor/templates/deployment.yaml#L100) add:
```yaml
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts  | nindent 10 }}
          {{- end }}
```

and above [snyk-monitor/templates/deployment.yaml#L227](https://github.com/snyk/kubernetes-monitor/blob/master/snyk-monitor/templates/deployment.yaml#L227) add:
```yaml
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes  | nindent 8 }}
{{- end }}
```
