### ISSUE TITLE
[🐛]Cannot upgrade Helm Chart from "1.103.0" -> "2.0.0"

### ISSUE THREAD

**Issue by ajchiarello** [snyk/kubernetes-monitor#1277]
- `kubernetes-monitor version 1.103.0` 
- `Cloud runtime RKE2`

### Expected behaviour
The upgrade to succeed.

### Actual behaviour
The upgrade fails with this error:

`cannot patch "snyk" with kind Deployment: Deployment.apps "snyk" is invalid: [spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn', spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].values: Required value: must be specified when `operator` is 'In' or 'NotIn']
`
### Steps to reproduce
Perform a helm update from 1.103.0 to 2.0.0. I am using the terraform helm provider, with the following values.yaml:
```
clusterName: "${var.project_name}"

excludedNamespaces:
${join("\n", formatlist("  - %s", local.exclude_namespaces))}

requests:
  cpu: "1500m"
  ephemeral-storage: "50Gi"
  memory: "2350Mi"

limits:
  cpu: "3200m"
  ephemeral-storage: "50Gi"
  memory: "5Gi"

strategy:
  type: Recreate
```
