### ISSUE TITLE
[🙏] Selectively add namespaces instead of excludedNamespaces

### ISSUE THREAD

**Issue by lukibahr** [snyk/kubernetes-monitor#1445]
**Describe the user need**
Instead of excluding namespaces via the `excludedNamespaces:` array, we would like to selectively add namespaces to a list, or choose namespaces by using label selectors, e.g.: 

```yaml
# Add selected namespaces
includedNamespaces:
  matchLabels: 
    key: value
#or 
includedNamespaces: 
  - namespaceA
  - namespaceB
```

**Describe expected behaviour**

snyk-monitor uses the exact list or selection of namespaces provided in the includedNamespaces field.

**Additional context**

Probably, the changes in the helm chart will not be that much, however, I don't know, if there are code-changes to be done.
